### ISSUE TITLE
3rd Milestone

### ISSUE THREAD

**Issue by fprochazka** [fprochazka/fi-muni-PA165-project#55]
# Requirements:

* User interface
    * [x] To start the web application you have to configure maven plugin (tomcat7 or jetty). It is very important that it’s super easy to start the web application from command line. So for example using tomcat7 plugin, the following sequence of commands should start the web application: “mvn clean install && cd web && mvn tomcat7:run”
    * [x] The web application must be available on the following HTTP context http://localhost:8080/pa165
    * [x] Your application should use in-memory database. This means that after application restart (killing web container and starting it again with mvn tomcat7:run) the data may be reset.
    * [x] Implement the user interface using Spring MVC or Angular JS. 
    * [ ] The user interface should allow to carry out all business functions of your system.
    * [x] You should fill in all the necessary data automatically. So for example you can use Web Listener to load data during Web Application startup.
    * [x] Make sure there are validations implemented on user interface.
    * [x] Your user interface should use either Facade layer or REST layer to access the system. Do not directly access database and do not directly use Service layer.
    * [x] The web interface layer may reside in separate maven module (if this is helpful).
    * [x] Each member of the team must implement (mostly independently, without copy-pasting) part of user interface. Including controller and view.
* REST layer:
    * [x] Your application should have a basic REST interface.
    * [x] At least one entity and operations on that entity must be exposed.
    * [x] This is mainly to demonstrate you can implement this, it’s not necessary to have all application functions accessible through this interface.
    * [x] The REST must be accessible at http://localhost:8080/pa165/rest
    * [x] it is not required to have the interface secured.
    * [x] You should include a README file with instructions how to test the REST interface (e.g. CURL commands for command line).
* Security:
    * [x] There should be at least 2 roles in the system (e.g. Administrator, User). Each role should have some differences in user interface or in capabilities.
    * [x] There should be login form (not HTTP Basic)
    * [x] Registration is NOT required. You can prefill the users and their passwords in the database.
    * [x] Password should not be saved in the database in open form.

**Comment by fprochazka** [comment]
Vezmu si REST, Security a UI pro usera. to by mělo posloužit jako dostatečnej zaklad pro vas, abyste v pohodě dali dohromady ten zbytek UI. Předpokládám, že tam toho bude povíc. 

Zkusím nejprve vytvořit UI na přihlášení, ať můžete začít řešit UI pro ostatní věci a pak do toho jen doděláme security. Může být?

**Comment by TomasSmid** [comment]
Jojo, s tim vsichni tri souhlasime, tak to prosim udelej jak se k tomu dostanes ;)

**Comment by TomasSmid** [comment]
Ok, s tim vsichni tri souhlasime, abys sis vzal a udelal, to co pises ;)
